version: '3'
services:
    app:
        build: .
        image: sample
        ports:
            - "9001:9001"
        volumes:
            - .:/app
        environment:
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            spring.datasource.url: "jdbc:mysql://db/sampleDB"
            spring.datasource.username: "mysql"
            spring.datasource.password: "mysql"